project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: "."

preserve_hierarchy: true

files:
  [
    {
      "source": "packages/library/src/i18n/translations/en.json",
      "translation": "packages/library/src/i18n/translations/%two_letters_code%.json",
    },
  ]
