link-workspace-packages: true
prefer-workspace-packages: true
save-workspace-protocol: false
blockExoticSubdeps: true
minimumReleaseAge: 4320
trustPolicy: "no-downgrade"
packages:
  - "packages/**/*"
  - "playground/**/*"
