name: "💬 Feature Proposal"
description: Suggest a new feature to be added
labels: ["Feature"]
body:
  - type: markdown
    attributes:
      value: |
        # Feature Proposal

        Welcome! 👋

        If you are interested in proposing a new feature or improvement to LightNet, then you are in the right place! 

        This template covers most of the questions you will be asked about your proposal.
        **This template is completely optional!** You are free to delete it, and use whatever format or length you prefer. You can always come back later to restructure your proposal.
  - type: textarea
    id: main
    attributes:
      label: Body
      value: |
        # Summary

        A brief, one or two sentence explanation of the proposal.

        # Background & Motivation

        Include any useful background detail that that explains why this feature is important.
        What are the problems that this feature sets out to solve? Why now? Be brief!

        It can be useful to illustrate your feature as a user problem in this section.
        (ex: "Users have reported that it is difficult to do X in LightNet today.")

        # Goals

        A **concise, bulleted-list** outlining the intended goals of this feature. 

        - What are the exact problems that you are trying to solve with this feature?
        - Separate these goals from the solution that you will outline below.
        - If this feature isn't approved, these goals can be used to develop alternative solutions.

        # Example

        If the proposal involves a new or changed API, then include a basic code example.
        Otherwise, omit this section if it's not applicable.
  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this feature.
          required: false
