name: Code style ✨

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  merge_group:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          cache: true
          require-lockfile: true
      - parallel:
          - run: pnpm typecheck
          - run: pnpm eslint . --report-unused-disable-directives --max-warnings 0
          - run: pnpm prettier . --check
