name: Release

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 20
  PNPM_VERSION: 9

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    if: ${{ github.repository_owner == 'LightNetDev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i

      - name: Release
        run: |
          pnpm changeset version
          git add .
          git commit -m "[ci] release"
          pnpm changeset publish
          git push --follow-tags
          git status
          git push
          git status

      # using changeset/action
      # - name: Create Release Pull Request
      #   id: changesets
      #   uses: changesets/action@v1
      #   with:
      #     version: pnpm run version
      #     publish: pnpm changeset publish
      #     commit: "[ci] release"
      #     title: "[ci] release"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
